version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: UserSetUp
      MYSQL_USER: root
      MYSQL_PASSWORD: Password
    volumes:
      - ./data:/var/lib/mysql
